### ISSUE TITLE
Some exotic v1 stacks aren't identified if @aws-cdk/core module isn't listed in modules

### ISSUE THREAD

**Issue by brandondahler** [cdklabs/awscdk-v1-stack-finder#610]
Stacks we have deployed contain a very limited set of information in the CDKMetadata modules section but are notably v1. 

The complete CDKMetadata resource in our stack is:

```
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.119.0
```

This appears to not be matching because the code assumes that `@aws-cdk/core` will be included in the list of modules on [this line](https://github.com/cdklabs/awscdk-v1-stack-finder/blob/main/src/index.ts#L190)
